services:
  mariadb:
    image: mariadb:10.11
    container_name: sgiu-mariadb
    restart: unless-stopped
    environment:
       
      MYSQL_ROOT_PASSWORD: Lucio1234
      MYSQL_DATABASE: sgiu_db
      MYSQL_USER: sgiu_user
      MYSQL_PASSWORD: sgiu_1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
 
volumes:
  mariadb_data:
